version: "3.7"

services:

    Gitea:
        image: "gitea/gitea:1.14.1"

        environment:
            - USER
            - USER_UID
            - USER_GID
            - GITEA__APP_NAME
            - GITEA__RUN_MODE
            - GITEA__server__LOCAL_ROOT_URL
        
        volumes:
            - "GiteaData:/data"
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"

        restart: "on-failure"
        networks:
            - "net"

        ports:
            - "3000:8080"
            - "222:22"

volumes:
    GiteaData:

networks:
    net:
        external: true
